# Generated by Django 6.0.7 on 2026-07-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("firms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="firms.firm",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
