services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: lexvault_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lexvault_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: lexvault_celery_worker
    restart: unless-stopped
    command: uv run celery -A config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - celery_venv:/app/.venv

  flower:
    build: .
    container_name: lexvault_flower
    restart: unless-stopped
    command: uv run celery -A config flower --port=5555
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker

volumes:
  postgres_data:
  celery_venv: