# Generated by Django 6.0.7 on 2026-07-09 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("firms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField()),
                (
                    "result_type",
                    models.CharField(
                        choices=[("found", "Found"), ("not_found", "Not Found")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to="firms.firm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relevance_score", models.FloatField()),
                ("rank", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="documents.chunk",
                    ),
                ),
                (
                    "search_query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="search.searchquery",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_searchquery_user_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchquery",
            constraint=models.CheckConstraint(
                condition=models.Q(("query_text__gt", "")), name="query_text_not_empty"
            ),
        ),
        migrations.AddIndex(
            model_name="citation",
            index=models.Index(fields=["search_query"], name="idx_citation_query"),
        ),
        migrations.AddIndex(
            model_name="citation",
            index=models.Index(fields=["chunk"], name="idx_citation_chunk"),
        ),
        migrations.AddConstraint(
            model_name="citation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("relevance_score__gte", 0), ("relevance_score__lte", 1)
                ),
                name="relevance_score_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="citation",
            constraint=models.CheckConstraint(
                condition=models.Q(("rank__gte", 1)), name="rank_at_least_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="citation",
            constraint=models.UniqueConstraint(
                fields=("search_query", "chunk"), name="unique_chunk_per_search_query"
            ),
        ),
        migrations.AddConstraint(
            model_name="citation",
            constraint=models.UniqueConstraint(
                fields=("search_query", "rank"), name="unique_rank_per_search_query"
            ),
        ),
    ]
